// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_W7WAryzm9b2ZO_kV5m_4QjqFT5MOHNM',
    appId: '1:520703414271:web:0f1f5520a0a8207472e1ca',
    messagingSenderId: '520703414271',
    projectId: 'point-game-12ded',
    authDomain: 'point-game-12ded.firebaseapp.com',
    databaseURL:
        'https://point-game-12ded-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'point-game-12ded.firebasestorage.app',
    measurementId: 'G-QC24QQ517G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSgmyax2wphP6RVL_dFKuV3BdU_GasC8M',
    appId: '1:520703414271:android:bf6a74d803160e1172e1ca',
    messagingSenderId: '520703414271',
    projectId: 'point-game-12ded',
    databaseURL:
        'https://point-game-12ded-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'point-game-12ded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvi30JNA6BneMybofRmm1PmS_ZbP33upA',
    appId: '1:520703414271:ios:ac2dea84a6ddc3d072e1ca',
    messagingSenderId: '520703414271',
    projectId: 'point-game-12ded',
    databaseURL:
        'https://point-game-12ded-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'point-game-12ded.firebasestorage.app',
    iosBundleId: 'com.ftvmzc.onepoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvi30JNA6BneMybofRmm1PmS_ZbP33upA',
    appId: '1:520703414271:ios:ac2dea84a6ddc3d072e1ca',
    messagingSenderId: '520703414271',
    projectId: 'point-game-12ded',
    databaseURL:
        'https://point-game-12ded-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'point-game-12ded.firebasestorage.app',
    iosBundleId: 'com.ftvmzc.onepoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_W7WAryzm9b2ZO_kV5m_4QjqFT5MOHNM',
    appId: '1:520703414271:web:8307978caa608a6372e1ca',
    messagingSenderId: '520703414271',
    projectId: 'point-game-12ded',
    authDomain: 'point-game-12ded.firebaseapp.com',
    databaseURL:
        'https://point-game-12ded-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'point-game-12ded.firebasestorage.app',
    measurementId: 'G-QF8K6Q38C9',
  );
}
